### ISSUE TITLE
ending xclip/xsel processes

### ISSUE THREAD

**Issue by mdlincoln** [mdlincoln/clipr#11]
The honorable BDR has raised an issue with the [pending CRAN submission](https://github.com/mdlincoln/clipr/commit/d14ed7f6b3473b34fbe2202a9a5a60a826f63368):

> It leaves xclip processes running, contrary to the CRAN policies.

I'm not sure if this is avoidable. From the [xclip docs](http://linux.die.net/man/1/xclip):

> The default action is to silently wait in the background for X selection requests (pastes) until another X application places data in the clipboard, at which point xclip exits silently. You can use the -verbose option to see if and when xclip actually receives selection requests from other X applications.

And the [xsel docs](http://www.vergenet.net/~conrad/software/xsel/xsel.1x.html)

> There is no X selection buffer. The selection mechanism in X11 is an interclient communication mediated by the X server each time any program wishes to know the selection contents, eg. to perform a middle mouse button paste. In order to implement modification of the selection(s) (in input, keep and exchange modes) this program detaches from the terminal, spawning a child process to supply the new selection(s) on demand. This child exits immediately when any other program takes over the selection(s), eg. when the user next selects some text in a terminal window or by running xsel -c.

@lmmx Am I right in thinking that there is no way to kill either of these processes without essentially wiping the clipboard?

**Comment by mdlincoln** [comment]
Closed by 05e59b4f4b04116442795dc76a014c9bfbecbe09

I'm putting a note in the docs explaining the behavior of xclip/xsel - hopefully this will satisfy the CRAN dragons.

**Comment by lmmx** [comment]
Sorry Matthew! Thought I'd replied by email already, been off sick this week. No, to my understanding I _think_ it should be possible to end the process without wiping the clipboard, the clipboard(s) is (are) a fundamental thing in Linux, xclip is an external program downloaded to deal with it.

I dual booted into Windows 8 this week which then proceeded to delete my bootloader, so I can't get back to Linux to test this ¬_¬ Apologies
