### ISSUE TITLE
Properly test clipr_available()

### ISSUE THREAD

**Issue by mdlincoln** [mdlincoln/clipr#21]
After putting much effort into getting clipr to test properly on Travis (#14), there's still the issue of correctly testing whether `clipr_available()` actually does the job properly. Since we're using a build matrix on Travis, it's possible to explicitly test this function when we know that clipr ought to work (when `DISPLAY=:90.0`) and when it ought to fail (`DISPLAY=""`).

This is the code I'm currently trying:

``` r
test_that("clipr_available fails when DISPLAY is not configured; 
succeeds when it is", {
  # Only run this test on Travis
  skip_if_not(identical(Sys.getenv("TRAVIS"), "true"))
  if (identical(Sys.getenv("DISPLAY"), ""))
    expect_false(clipr_available())
  if (identical(Sys.getenv("DISPLAY"), ":90.0"))
    expect_true(clipr_available())
})
````

Unfortunately, this test appears to fail when it ought to pass, `clipr_available()` returning `FALSE` when the Travis environment _ought_ to be properly configured. Oddly, it [fails even when incorporating the fix](https://travis-ci.org/mdlincoln/clipr/jobs/178779393) from #20

**Comment by krivit** [comment]
For what it's worth, I just tested the version from #20, and it returns the correct answer within X (TRUE) and on a bare shell (FALSE).

I don't know TravisCI well enough to speculate what's going on. Can the R process see the DISPLAY variables? Is R under Travis built with X capabilities? What does `capabilities("X11")` say?

**Comment by mdlincoln** [comment]
Turns out I had the `DISPLAY` variable set incorrectly - it should have been `:99.0` instead of `:90.0` :face_with_head_bandage: The fix passes on Travis now.
