### ISSUE TITLE
Warning when writing "" to clipboard

### ISSUE THREAD

**Issue by jennybc** [mdlincoln/clipr#22]
I don't understand why this gives a warning.

``` r
clipr::write_clip("")
#> Warning: problem writing to connection
```

Because it does seem to clear the clipboard?

**Comment by mdlincoln** [comment]
Some kind of weirdness with the underlying `pipe()` call.

**Comment by mdlincoln** [comment]
As with all things clipr, this is still being tricky on Linux... still working on a fix.

**Comment by mdlincoln** [comment]
OK, 0f6c9449fdcd2fd21994a448acd9bdb04f09bbff seems to have done it.
