### ISSUE TITLE
Need an extra column name when row.names=TRUE

### ISSUE THREAD

**Issue by kwstat** [mdlincoln/clipr#31]
I'm on Windows 7, if it matters.  When I have an object that I write to the clipboard with row.names=TRUE, the column names need an extra delimiter inserted before the first column name.  Otherwise the column names end up shifted left one column when pasting into Excel.

```
dat <- matrix(1:4, 2)
rownames(dat) <- c('a','b')
colnames(dat) <- c('c','d')
dat
library(clipr)
clipr::write_clip(dat, row.names=TRUE, col.names=TRUE, sep=",")
# paste content below
c,d
a,1,3
b,2,4
```

The desired result should look like this (with an extra delimeter in front of "c"):
```
,c,d
a,1,3
b,2,4
```

**Comment by mdlincoln** [comment]
Thanks for the report - I'll take a look.
