### ISSUE TITLE
Consider renaming warn_interactive()

### ISSUE THREAD

**Issue by jennybc** [mdlincoln/clipr#46]
I strongly associate "warn" with `warning()` and therefore find it non-obvious that `warn_interactive()` throws an error:

``` r
warn_interactive <- function() {
  stop(msg_interactive())
}
```

Would you considering using "stop" or "abort" in this name, instead of "warn"?

I know this is just an internal function, but I'm reading things carefully right now, to rework some stuff in reprex. I want to make sure I really understand when clipr can and cannot touch the system clipboard.

**Comment by mdlincoln** [comment]
Yep, a logical suggestion! Will change.
