### ISSUE TITLE
write_clip should support copy to HTML Format

### ISSUE THREAD

**Issue by matbmeijer** [mdlincoln/clipr#53]
Hi @mdlincoln ,

First of all, thank you for this cross-platform solution, I think it's great. I wanted to ask if it would be possible to add a parameter to the `write_clip` that allows to format tables in HTML format in the clipboard:
![HTML Format](https://user-images.githubusercontent.com/16921170/81058120-13834a80-8ece-11ea-9722-eeb5980d6c2e.png)

This would allow to have a multi-software interaction between R, Powerpoint, Word, and most other HTML supporting platforms.

I found this, which might be related cross-platform solutions and pandoc solution:
* https://superuser.com/questions/912712/how-to-send-rich-text-to-the-clipboard-from-command-line

windows only:
* https://www.reddit.com/r/PowerShell/comments/9ugprj/exporting_to_your_clipboard_as_html/
* https://docs.microsoft.com/en-us/windows/win32/dataxchg/html-clipboard-format

Thank you!

**Comment by mdlincoln** [comment]
Thanks, I'm glad you are finding clipr useful.

The function you're looking for is `knitr::kable()`, which can format data frames into HTML, Markdown, and LaTeX strings, among other formats. Combine that with `write_clip()` and you'll have what you're looking for:

```
iris %>%
    knitr::kable(format = "html") %>%
    write_clip()
```

**Comment by matbmeijer** [comment]
Hi @mdlincoln ,

I think you missed my point, I am sorry if I did not explain myself properly.

I know I can do that with `kable()`, that but I cannot paste a table then in HTML format. This is what I get in Powerpoint when I apply your code with the following code:
```
iris %>% 
  head(5) %>%
  knitr::kable(format = "html") %>%
  clipr::write_clip()
````
![result](https://user-images.githubusercontent.com/16921170/81073084-63bad680-8ee7-11ea-93dc-c268d006d6d4.png)

As mentioned before, this is only raw text:
![format_options](https://user-images.githubusercontent.com/16921170/81073223-9a90ec80-8ee7-11ea-91dc-2576fbc3589d.png)

But this is what I think would be great to have:
![what I want](https://user-images.githubusercontent.com/16921170/81073486-01aea100-8ee8-11ea-9dd1-7519b5e14b58.png)

Which should be possible given there is a default HTML format output:
![HTML Format](https://user-images.githubusercontent.com/16921170/81073558-1723cb00-8ee8-11ea-8106-b1768af50fce.png)


I hope my point is understood! This would allow a much better cross-software integration in common daily workflows (copy tables from R and paste them in pptx for example, or in word, etc.)

**Comment by matbmeijer** [comment]
Hi @mdlincoln ,

I got a really simplistic formula to work in Windows, Linux & Mac should be easier:
```r
clipboard_as_html <- function(df, rownames=FALSE, caption = NULL){
  html_df <- knitr::kable(df, format = "html", caption = caption, row.names = FALSE)
  temp_dir <- tempdir()
  file_path <- file.path(temp_dir, "write_to_clipboard.txt")
  write(html_df, file_path)
  file_path <- normalizePath(file_path)
  first_command <- sprintf("$text = Get-Content %s -Raw", file_path)
  second_command <- "$text | Set-Clipboard -AsHtml"
  system2("powershell", args = paste(c(first_command, second_command), collapse = ";"))
  unlink(file_path)
}

clipboard_as_html(df = head(iris, 5))
```
This got me the results I wanted. Maybe a good idea to include?

![iris](https://user-images.githubusercontent.com/16921170/81076790-610eb000-8eec-11ea-85f1-e8b010fc7ddd.png)
