### ISSUE TITLE
Running xsel hangs on RStudio

### ISSUE THREAD

**Issue by csgillespie** [mdlincoln/clipr#54]
Running `system2("xsel", "--clipboard")` causes my machine to hang (could be an i3 thing) when using RStudio console.

Changing

```
has_xsel <- function() has_util(c("xsel", "--clipboard"))
```
to
```
#linux_clipboard.R
has_xsel <- function() has_util(c("xsel", "--clipboard", "--output"))
```
Solves my issues.

The documentation suggests that this is the correct thing to do. It states that the behaviour depends on whether input / output are ttys:

       By default, this program outputs the selection without modification if both standard input  and
       standard  output  are  terminals (ttys). Otherwise, the current selection is output if standard
       output is not a terminal (tty), and the selection is set from standard input if standard  input
       is not a terminal (tty). If any input or output options are given then the program behaves only
       in the requested mode.
       If both input and output is required then the previous selection is  output  before  being  re‐
       placed by the contents of standard input.

---
  * See https://github.com/rstudio/rstudio/issues/7924 for the back story
 * @kevinushey found the solution

**Comment by mdlincoln** [comment]
Thanks for this detailed report. I'll be able to take a closer look shortly.

**Comment by mdlincoln** [comment]
Thanks for your patience @csgillespie. It looks like this bug also caused `read_clip()` to hang when run from RStudio - my colleague who has a Linux machine using the KWin window manager helped to diagnose that. Can you give this a spin and check if read/write is working for you?

`devtools::install_github(“mdlincoln/clipr”, ref=“xsel-read-output”)`

**Comment by csgillespie** [comment]
Seems to work for me. 

To test I uninstalled clip

```
sudo apt remove xclip
```
Then ran
```
devtools::install_github("mdlincoln/clipr", ref="xsel-read-output")
clipr::write_clip("hello")
clipr::read_clip()
```
in RStudio

**Comment by mdlincoln** [comment]
Alright. I'll ship this off to CRAN.

**Comment by mdlincoln** [comment]
Now shipped to CRAN.

**Comment by kevinushey** [comment]
Thank you for taking a look so quickly!
