### ISSUE TITLE
Issue with Wayland?

### ISSUE THREAD

**Issue by ekianjo** [mdlincoln/clipr#58]
On Linux, no issues with X11, but when running with Wayland, I get the following error:

"Clipboard on X11 requires that the DISPLAY envvar be configured."

ANy work-around?

**Comment by mmahmoudian** [comment]
That is because both linux clipboard softwares implemented in clipr are X11-specific (namedly xclip and xsel). The most common wayland clipboard software is [wl-clipboard](https://github.com/bugaevc/wl-clipboard) and less common one (which doesn't even exist in Arch repo or AUR) is [wclip](https://gitlab.com/j64wang/wclip) which looks like an abandoned project.

Anyways, @mdlincoln would you please assign this to me. I'll try to create a PR for wl-clipboard

**Comment by mdlincoln** [comment]
@mmahmoudian thank you, I'll be happy to review a PR! Note that an earlier attempt was made with #51 however it lacked tests that could be run on CI.

**Comment by mmahmoudian** [comment]
@mdlincoln My experience with Travis is not extensive compared to Github Actions or Gitlab CI/CD so it might take a while but I'll do my best. Let me know if you found a better and more experienced person that you wanted to assign this to though.

**Comment by mdlincoln** [comment]
@mmahmoudian FYI I have some time this week to migrate the builds over to GitHub actions (I have wanted to get off of travis for some time now, this is a good reason!)

**Comment by mmahmoudian** [comment]
@mdlincoln I'm super busy these days and so far haven't had time to work on this. As far as I've read the code and the various attempts @nacnudus, everything "should"  work and I cannot figure out what the problem can be. I will try to allocate some time this week to look into this, but I would still recommend to use Github Actions as it was a smooth experience for me and is of course well integrated into Github. If you need some template to kickstart the migration, take a look at my R package's workflows:
https://github.com/mmahmoudian/sivs/

**Comment by mdlincoln** [comment]
On the `actions` branch I've got all the existing tests running properly again, and am now trying to get a headless wayland testing environment set up. Although I can get wl-copy / wl-paste installed, I'm running into an error `Failed to connect to a Wayland server` when trying to call the commands: https://github.com/mdlincoln/clipr/runs/4239802322?check_suite_focus=true 

@bugaevc would you happen to know how to set up a good test environment for the wl-clipboard utils via github acitons?

**Comment by mmahmoudian** [comment]
@mdlincoln This might be helpful:
https://github.com/bugaevc/wl-clipboard/issues/114

As far as I understand, you can add a line before  [line 116 of R-CMD-check.yaml](https://github.com/mdlincoln/clipr/blob/c28a8ce62087ddcdfd4eac7d73571676da574adb/.github/workflows/R-CMD-check.yaml#L116) and add `export WAYLAND_DISPLAY=wayland-1`

**Comment by mdlincoln** [comment]
I haven't forgotten about this, but I admit to being quite stuck on how to set up headless testing with Wayland. I've got a SO question up now documenting our challenges: https://stackoverflow.com/questions/70247332/use-headless-wayland-sway-when-testing-on-github-actions
