### ISSUE TITLE
Clipboard for Shiny apps, ala github

### ISSUE THREAD

**Issue by smbache** [mdlincoln/clipr#9]
How about adding ZeroClipboard functionality for easy clipboarding in e.g. Shiny apps?
See https://github.com/zeroclipboard/zeroclipboard

AFAIK this is what Github uses for its "copy-to-clipboard" functionality...

**Comment by mdlincoln** [comment]
What you're describing sounds like a browser widget for Shiny that writes to the _user's_ clipboard, not to the clipboard of the system actually running R. This seems like the territory of the browser interface, not server-side code. While that sounds useful, I think it is outside the bounds of this package.

**Comment by smbache** [comment]
Sort of -- in a shiny app you still need the server to communicate the clipboard content in a manner that the user can reach...

But fair enough (would have been nice)
